(subdir schulze
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinNums.ml BinNums.mli
    Datatypes.ml Datatypes.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    MatN.ml MatN.mli
    Nat.ml Nat.mli
    OrelN.ml OrelN.mli
    Schulze.ml Schulze.mli
    SemimoduleN.ml SemimoduleN.mli
    Specif.ml Specif.mli
    Structures.ml Structures.mli)
  (theories Stdlib HB elpi_elpi elpi Semiring Examples))
  (library 
    (name schulze)
    (wrapped false)))

(subdir widestshortestpath
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinNums.ml BinNums.mli
    Datatypes.ml Datatypes.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    MatN.ml MatN.mli
    Nat.ml Nat.mli
    OrelN.ml OrelN.mli
    SemimoduleN.ml SemimoduleN.mli
    Specif.ml Specif.mli
    Structures.ml Structures.mli
    WidestShortestPath.ml WidestShortestPath.mli)
  (theories Stdlib HB elpi_elpi elpi Semiring Examples))
  (library
    (name widestshortestpath)
    (wrapped false)))


(subdir shortestpath
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinNums.ml BinNums.mli
    Datatypes.ml Datatypes.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    MatN.ml MatN.mli
    Nat.ml Nat.mli
    OrelN.ml OrelN.mli
    SemimoduleN.ml SemimoduleN.mli
    Shortestpath.ml Shortestpath.mli
    Specif.ml Specif.mli
    Structures.ml Structures.mli)
  (theories Stdlib HB elpi_elpi elpi Semiring Examples))
  (library
    (name shortestpath)
    (wrapped false)))


(subdir wikimedia
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinNums.ml BinNums.mli
    Datatypes.ml Datatypes.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    MatN.ml MatN.mli
    Nat.ml Nat.mli
    OrelN.ml OrelN.mli
    SemimoduleN.ml SemimoduleN.mli
    Specif.ml Specif.mli
    Structures.ml Structures.mli
    Wikimedia.ml Wikimedia.mli)
  (theories Stdlib HB elpi_elpi elpi Semiring Examples))
  (library
    (name wikimedia)
    (wrapped false)))

(subdir viterbi
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinInt.ml BinInt.mli
    BinNums.ml BinNums.mli
    BinPos.ml BinPos.mli
    Datatypes.ml Datatypes.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    MatN.ml MatN.mli
    Nat.ml Nat.mli
    OrelN.ml OrelN.mli
    PosDef.ml PosDef.mli
    QArith_base.ml QArith_base.mli
    Qreduction.ml Qreduction.mli
    SemimoduleN.ml SemimoduleN.mli
    Specif.ml Specif.mli
    Structures.ml Structures.mli
    Viterbi.ml Viterbi.mli)
  (theories Stdlib HB elpi_elpi elpi Semiring Examples))
  (library
    (name viterbi)
    (wrapped false)))

(subdir fivegslicing
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinNums.ml BinNums.mli
    Datatypes.ml Datatypes.mli
    FiveGNetworkSlicing.ml FiveGNetworkSlicing.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    MatN.ml MatN.mli
    Nat.ml Nat.mli
    OrelN.ml OrelN.mli
    SemimoduleN.ml SemimoduleN.mli
    Specif.ml Specif.mli
    Structures.ml Structures.mli)
  (theories Stdlib HB elpi_elpi elpi Semiring Examples))
  (library
    (name fivegslicing)
    (wrapped false)))
