(subdir schulze
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinNums.ml BinNums.mli
    Datatypes.ml Datatypes.mli
    Definitions.ml Definitions.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    Mat.ml Mat.mli
    Nat.ml Nat.mli
    Path.ml Path.mli
    Schulze.ml Schulze.mli)
  (theories Stdlib Semiring Examples))
  (library 
    (name schulze)
    (wrapped false)))

(subdir widestshortestpath
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinNums.ml BinNums.mli
    Datatypes.ml Datatypes.mli
    Definitions.ml Definitions.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    Mat.ml Mat.mli
    Nat.ml Nat.mli
    Path.ml Path.mli
    WidestShortestPath.ml WidestShortestPath.mli)
  (theories Stdlib Semiring Examples))
  (library
    (name widestshortestpath)
    (wrapped false)))


(subdir shortestpath
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinNums.ml BinNums.mli
    Datatypes.ml Datatypes.mli
    Definitions.ml Definitions.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    Mat.ml Mat.mli
    Nat.ml Nat.mli
    Path.ml Path.mli
    Shortestpath.ml Shortestpath.mli)
  (theories Stdlib Semiring Examples))
  (library
    (name shortestpath)
    (wrapped false)))


(subdir wikimedia
 (rocq.extraction
  (prelude Extraction)
  (extracted_files
    BinNums.ml BinNums.mli
    Datatypes.ml Datatypes.mli
    Definitions.ml Definitions.mli
    List.ml List.mli
    ListDef.ml ListDef.mli
    Mat.ml Mat.mli
    Nat.ml Nat.mli
    Path.ml Path.mli
    Wikimedia.ml Wikimedia.mli)
  (theories Stdlib Semiring Examples))
  (library
    (name wikimedia)
    (wrapped false)))